---
title: "Example Slides"
output:
  ioslides_presentation: default
  md_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Guidelines

This presentation is an example on how you should submit your slides. You can find out more about our guidelines on our website (<https://user2020muc.r-project.org/>).  
The website also has a full list of all the guidelines. 
For illustration, we only show a selection of these guidelines. 

## R Markdown

This is an R Markdown presentation. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.  
There also is a cheatsheet, see <https://rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf>.  

Please submit your presentation/poster in markdown as it will enable blind people to use screen reading software or braille displays to follow the details (e.g. code) of talks.

## Requirements

* Length: 
  + contributed: 10-15 minutes
  + lightning: 3-5 minutes
  + poster: 0.5-1 minute
* Video should be picture in picture (slides in the background, speaker smaller in the foreground), or slides and speaker should be on splitted screens.
* Please let us know if your video requires a content warning (e.g. due to unavoidable presentation of offensive or sexualised material, or due to flashing images).

*** 

### Video of the speaker

* Best would be a neutral background and low or no background audio.
* Your face should be clearly visible (people who are deaf or hard of hearing may be able to lip-read).
* Speak clearly.
* Please pace yourself, so the audience can integrate both audio and visual information. Graphics, pictures, videos, and memes should be described audibly.
* Speak every word on a slide, read long excerpts aloud.
* Verbally describe images.

*** 

### Slides
* Use large sans serif fonts (as a guide 28-32pt or above for regular text).
* Use high contrast.
* Make sure slides are discernable for color blind users.
* Use more than color to communicate information (color coding cannot be understood by people who are blind or colorblind).
* Do not use flashing videos or images.
* Avoid using animations (Unless with a detailed audio description).
* Provide a text equivalent for graphics, but not for graphics that are only meant for decoration.
